### ISSUE TITLE
install packages from multiple repos into same node_modules folder

### ISSUE THREAD

**Issue by lc4377** [maxleiko/npmi#18]
Is there a way to install npm packages in a different directory? 
Use case: I have multiple local repos. i want to run npmi on all those repos. But the dependencies for all those repos should be installed into a single node_modules folder that is located somewhere else

**Comment by maxleiko** [comment]
Hello @lc4377 

If I understand your need completely, there will be edge cases where one node_modules folder for all your local repos won't be enough. For instance, if you have two different repos with the same dependency in two different versions, you'll have a conflict that npm solves by installing the specific version in the respective module's node_modules.

That being said, what you want to achieve requires some pre-process, I'd advise you to parse all your local repos `package.json` files in order to identify their `name`, and then ask `npmi` to simply install them all somewhere using the `path` option.

Anyway, this is not a bug, nor a feature request for `npmi`. This kind of question should be asked on [stackoverflow](https://stackoverflow.com/) imo.
