### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by SamVerschueren** [maxleiko/npmi#7]
Would it be possible to release this package? I need to get rid of the npm@2.x dependency.

**Comment by maxleiko** [comment]
@SamVerschueren you can start by using the `npmi@next` version which is exactly the `2.0.1-alpha` and has `npm@^3` as dependency.

I will release the 2.0.1 soon.

**Comment by maxleiko** [comment]
http://registry.npmjs.com/npmi/next

**Comment by SamVerschueren** [comment]
Thanks! It did the trick :).

**Comment by binduwavell** [comment]
I use bithound to track deps for one of my projects. They are fingering npmi as being insecure because the released version is still relying on a pretty old npm. I don't actually depend on npmi directly, I get it transatively through a dev dependency (npm-check-updates) so I can't update. I will also ask them to take a look at this. I was wondering if you could provide a sense of how close you are to releasing 2.0.1?

**Comment by maxleiko** [comment]
@binduwavell : As I've had no negative feedback with the `2.0.1-alpha` I guess I could release the `2.0.1` today. I'll let you know as soon as I've done so.

**Comment by maxleiko** [comment]
@binduwavell `v2.0.1` released
